changelog:
  categories:
    - title: Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - build
    - title: Updated Dependencies
      labels:
        - dependencies
      exclude:
        labels:
          - build
