formatting:
  NoWildcardImports:
    active: false

style:
  WildcardImport:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'
